"""expand family memory domain

Revision ID: aa0f1119c8de
Revises: 2b4097f46f32
Create Date: 2026-08-13 14:36:28.672640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa0f1119c8de'
down_revision: Union[str, Sequence[str], None] = '2b4097f46f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_persons',
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('family_member_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', 'family_member_id')
    )
    op.add_column('family_members', sa.Column('family_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'family_members', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    op.add_column('memories', sa.Column('family_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('memories_ibfk_1'), 'memories', type_='foreignkey')
    op.create_foreign_key(None, 'memories', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    op.drop_column('memories', 'family_member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('family_member_id', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.create_foreign_key(op.f('memories_ibfk_1'), 'memories', 'family_members', ['family_member_id'], ['id'], ondelete='CASCADE')
    op.drop_column('memories', 'family_id')
    op.drop_constraint(None, 'family_members', type_='foreignkey')
    op.drop_column('family_members', 'family_id')
    op.drop_table('memory_persons')
    op.drop_table('media_assets')
    op.drop_table('families')
    # ### end Alembic commands ###
