"""add memory source session

Revision ID: b2951a5cb807
Revises: 586c4bdbdb44
Create Date: 2026-08-14 17:07:47.060025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2951a5cb807'
down_revision: Union[str, Sequence[str], None] = '586c4bdbdb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('source_session_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'memories', ['source_session_id'])
    op.create_foreign_key(None, 'memories', 'chat_sessions', ['source_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_constraint(None, 'memories', type_='unique')
    op.drop_column('memories', 'source_session_id')
    # ### end Alembic commands ###
